<!-- Modal -->
<div class="modal fade" id="create" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Adicionar</h4>
            </div>
            <div class="modal-body">
                <div id="message_add"></div>
                <form action="<?= base_url('painel/paginas/store') ?>">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="">Nome da página</label>
                                <input type="text" name="title" class="form-control">
                            </div>
                        </div>
                    </div>
                    <style>
                        .select2{font-family:'FontAwesome'!important;}
                        .select2-results__option{font-family:'FontAwesome'!important;}
                    </style>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="icon">Ícone</label>
                                <select name="icon" class="form-control">
                                    <option></option>
                                    <option value="glass">&#xf000; glass</option>
                                    <option value="music">&#xf001; music</option>
                                    <option value="search">&#xf002; search </option>
                                    <option value="envelope-alt">&#xf003; envelope-alt </option>
                                    <option value="heart">&#xf004; heart</option>
                                    <option value="star">&#xf005; star </option>
                                    <option value="star-empty">&#xf006; star-empty </option>
                                    <option value="user">&#xf007; user </option>
                                    <option value="film">&#xf008; film </option>
                                    <option value="th-large">&#xf009; th-large </option>
                                    <option value="th">&#xf00a; th </option>
                                    <option value="th-list">&#xf00b; th-list</option>
                                    <option value="ok">&#xf00c; ok </option>
                                    <option value="remove">&#xf00d; remove </option>
                                    <option value="zoom-in">&#xf00e; zoom-in</option>
                                    <option value="zoom-out">&#xf010; zoom-out </option>
                                    <option value="off">&#xf011; off</option>
                                    <option value="signal">&#xf012; signal </option>
                                    <option value="cog">&#xf013; cog</option>
                                    <option value="trash">&#xf014; trash</option>
                                    <option value="home">&#xf015; home </option>
                                    <option value="file-alt">&#xf016; file-alt </option>
                                    <option value="time">&#xf017; time </option>
                                    <option value="road">&#xf018; road </option>
                                    <option value="download-alt">&#xf019; download-alt </option>
                                    <option value="download">&#xf01a; download </option>
                                    <option value="upload">&#xf01b; upload </option>
                                    <option value="inbox">&#xf01c; inbox</option>
                                    <option value="play-circle">&#xf01d; play-circle</option>
                                    <option value="repeat">&#xf01e; repeat </option>
                                    <option value="refresh">&#xf021; refresh</option>
                                    <option value="list-alt">&#xf022; list-alt </option>
                                    <option value="lock">&#xf023; lock </option>
                                    <option value="flag">&#xf024; flag </option>
                                    <option value="headphones">&#xf025; headphones </option>
                                    <option value="volume-off">&#xf026; volume-off </option>
                                    <option value="volume-down">&#xf027; volume-down</option>
                                    <option value="volume-up">&#xf028; volume-up</option>
                                    <option value="qrcode">&#xf029; qrcode </option>
                                    <option value="barcode">&#xf02a; barcode</option>
                                    <option value="tag">&#xf02b; tag</option>
                                    <option value="tags">&#xf02c; tags </option>
                                    <option value="book">&#xf02d; book </option>
                                    <option value="bookmark">&#xf02e; bookmark </option>
                                    <option value="print">&#xf02f; print</option>
                                    <option value="camera">&#xf030; camera </option>
                                    <option value="font">&#xf031; font </option>
                                    <option value="bold">&#xf032; bold </option>
                                    <option value="italic">&#xf033; italic </option>
                                    <option value="text-height">&#xf034; text-height</option>
                                    <option value="text-width">&#xf035; text-width </option>
                                    <option value="align-left">&#xf036; align-left </option>
                                    <option value="align-center">&#xf037; align-center </option>
                                    <option value="align-right">&#xf038; align-right</option>
                                    <option value="align-justify">&#xf039; align-justify</option>
                                    <option value="list">&#xf03a; list </option>
                                    <option value="indent-left">&#xf03b; indent-left</option>
                                    <option value="indent-right">&#xf03c; indent-right </option>
                                    <option value="facetime-video">&#xf03d; facetime-video </option>
                                    <option value="picture">&#xf03e; picture</option>
                                    <option value="pencil">&#xf040; pencil </option>
                                    <option value="map-marker">&#xf041; map-marker </option>
                                    <option value="adjust">&#xf042; adjust </option>
                                    <option value="tint">&#xf043; tint </option>
                                    <option value="edit">&#xf044; edit </option>
                                    <option value="share">&#xf045; share</option>
                                    <option value="check">&#xf046; check</option>
                                    <option value="move">&#xf047; move </option>
                                    <option value="step-backward">&#xf048; step-backward</option>
                                    <option value="fast-backward">&#xf049; fast-backward</option>
                                    <option value="backward">&#xf04a; backward </option>
                                    <option value="play">&#xf04b; play </option>
                                    <option value="pause">&#xf04c; pause</option>
                                    <option value="stop">&#xf04d; stop </option>
                                    <option value="forward">&#xf04e; forward</option>
                                    <option value="fast-forward">&#xf050; fast-forward </option>
                                    <option value="step-forward">&#xf051; step-forward </option>
                                    <option value="eject">&#xf052; eject</option>
                                    <option value="chevron-left">&#xf053; chevron-left </option>
                                    <option value="chevron-right">&#xf054; chevron-right</option>
                                    <option value="plus-sign">&#xf055; plus-sign</option>
                                    <option value="minus-sign">&#xf056; minus-sign </option>
                                    <option value="remove-sign">&#xf057; remove-sign</option>
                                    <option value="ok-sign">&#xf058; ok-sign</option>
                                    <option value="question-sign">&#xf059; question-sign</option>
                                    <option value="info-sign">&#xf05a; info-sign</option>
                                    <option value="screenshot">&#xf05b; screenshot </option>
                                    <option value="remove-circle">&#xf05c; remove-circle</option>
                                    <option value="ok-circle">&#xf05d; ok-circle</option>
                                    <option value="ban-circle">&#xf05e; ban-circle </option>
                                    <option value="arrow-left">&#xf060; arrow-left </option>
                                    <option value="arrow-right">&#xf061; arrow-right</option>
                                    <option value="arrow-up">&#xf062; arrow-up </option>
                                    <option value="arrow-down">&#xf063; arrow-down </option>
                                    <option value="share-alt">&#xf064; share-alt</option>
                                    <option value="resize-full">&#xf065; resize-full</option>
                                    <option value="resize-small">&#xf066; resize-small </option>
                                    <option value="plus">&#xf067; plus </option>
                                    <option value="minus">&#xf068; minus</option>
                                    <option value="asterisk">&#xf069; asterisk </option>
                                    <option value="exclamation-sign">&#xf06a; exclamation-sign </option>
                                    <option value="gift">&#xf06b; gift </option>
                                    <option value="leaf">&#xf06c; leaf </option>
                                    <option value="fire">&#xf06d; fire </option>
                                    <option value="eye-open">&#xf06e; eye-open </option>
                                    <option value="eye-close">&#xf070; eye-close</option>
                                    <option value="warning-sign">&#xf071; warning-sign </option>
                                    <option value="plane">&#xf072; plane</option>
                                    <option value="calendar">&#xf073; calendar </option>
                                    <option value="random">&#xf074; random </option>
                                    <option value="comment">&#xf075; comment</option>
                                    <option value="magnet">&#xf076; magnet </option>
                                    <option value="chevron-up">&#xf077; chevron-up </option>
                                    <option value="chevron-down">&#xf078; chevron-down </option>
                                    <option value="retweet">&#xf079; retweet</option>
                                    <option value="shopping-cart">&#xf07a; shopping-cart</option>
                                    <option value="folder-close">&#xf07b; folder-close </option>
                                    <option value="folder-open">&#xf07c; folder-open</option>
                                    <option value="resize-vertical">&#xf07d; resize-vertical</option>
                                    <option value="resize-horizontal">&#xf07e; resize-horizontal</option>
                                    <option value="bar-chart">&#xf080; bar-chart</option>
                                    <option value="twitter-sign">&#xf081; twitter-sign </option>
                                    <option value="facebook-sign">&#xf082; facebook-sign</option>
                                    <option value="camera-retro">&#xf083; camera-retro </option>
                                    <option value="key">&#xf084; key</option>
                                    <option value="cogs">&#xf085; cogs </option>
                                    <option value="comments">&#xf086; comments </option>
                                    <option value="thumbs-up-alt">&#xf087; thumbs-up-alt</option>
                                    <option value="thumbs-down-alt">&#xf088; thumbs-down-alt</option>
                                    <option value="star-half">&#xf089; star-half</option>
                                    <option value="heart-empty">&#xf08a; heart-empty</option>
                                    <option value="signout">&#xf08b; signout</option>
                                    <option value="linkedin-sign">&#xf08c; linkedin-sign</option>
                                    <option value="pushpin">&#xf08d; pushpin</option>
                                    <option value="external-link">&#xf08e; external-link</option>
                                    <option value="signin">&#xf090; signin </option>
                                    <option value="trophy">&#xf091; trophy </option>
                                    <option value="github-sign">&#xf092; github-sign</option>
                                    <option value="upload-alt">&#xf093; upload-alt </option>
                                    <option value="lemon">&#xf094; lemon</option>
                                    <option value="phone">&#xf095; phone</option>
                                    <option value="check-empty">&#xf096; check-empty</option>
                                    <option value="bookmark-empty">&#xf097; bookmark-empty </option>
                                    <option value="phone-sign">&#xf098; phone-sign </option>
                                    <option value="twitter">&#xf099; twitter</option>
                                    <option value="facebook">&#xf09a; facebook </option>
                                    <option value="github">&#xf09b; github </option>
                                    <option value="unlock">&#xf09c; unlock </option>
                                    <option value="credit-card">&#xf09d; credit-card</option>
                                    <option value="rss">&#xf09e; rss</option>
                                    <option value="hdd">&#xf0a0; hdd</option>
                                    <option value="bullhorn">&#xf0a1; bullhorn </option>
                                    <option value="bell">&#xf0a2; bell </option>
                                    <option value="certificate">&#xf0a3; certificate</option>
                                    <option value="hand-right">&#xf0a4; hand-right </option>
                                    <option value="hand-left">&#xf0a5; hand-left</option>
                                    <option value="hand-up">&#xf0a6; hand-up</option>
                                    <option value="hand-down">&#xf0a7; hand-down</option>
                                    <option value="circle-arrow-left">&#xf0a8; circle-arrow-left</option>
                                    <option value="circle-arrow-right">&#xf0a9; circle-arrow-right </option>
                                    <option value="circle-arrow-up">&#xf0aa; circle-arrow-up</option>
                                    <option value="circle-arrow-down">&#xf0ab; circle-arrow-down</option>
                                    <option value="globe">&#xf0ac; globe</option>
                                    <option value="wrench">&#xf0ad; wrench </option>
                                    <option value="tasks">&#xf0ae; tasks</option>
                                    <option value="filter">&#xf0b0; filter </option>
                                    <option value="briefcase">&#xf0b1; briefcase</option>
                                    <option value="fullscreen">&#xf0b2; fullscreen </option>
                                    <option value="group">&#xf0c0; group</option>
                                    <option value="link">&#xf0c1; link </option>
                                    <option value="cloud">&#xf0c2; cloud</option>
                                    <option value="beaker">&#xf0c3; beaker </option>
                                    <option value="cut">&#xf0c4; cut</option>
                                    <option value="copy">&#xf0c5; copy </option>
                                    <option value="paper-clip">&#xf0c6; paper-clip </option>
                                    <option value="save">&#xf0c7; save </option>
                                    <option value="sign-blank">&#xf0c8; sign-blank </option>
                                    <option value="reorder">&#xf0c9; reorder</option>
                                    <option value="list-ul">&#xf0ca; list-ul</option>
                                    <option value="list-ol">&#xf0cb; list-ol</option>
                                    <option value="strikethrough">&#xf0cc; strikethrough</option>
                                    <option value="underline">&#xf0cd; underline</option>
                                    <option value="table">&#xf0ce; table</option>
                                    <option value="magic">&#xf0d0; magic</option>
                                    <option value="truck">&#xf0d1; truck</option>
                                    <option value="pinterest">&#xf0d2; pinterest</option>
                                    <option value="pinterest-sign">&#xf0d3; pinterest-sign </option>
                                    <option value="google-plus-sign">&#xf0d4; google-plus-sign </option>
                                    <option value="google-plus">&#xf0d5; google-plus</option>
                                    <option value="money">&#xf0d6; money</option>
                                    <option value="caret-down">&#xf0d7; caret-down </option>
                                    <option value="caret-up">&#xf0d8; caret-up </option>
                                    <option value="caret-left">&#xf0d9; caret-left </option>
                                    <option value="caret-right">&#xf0da; caret-right</option>
                                    <option value="columns">&#xf0db; columns</option>
                                    <option value="sort">&#xf0dc; sort </option>
                                    <option value="sort-down">&#xf0dd; sort-down</option>
                                    <option value="sort-up">&#xf0de; sort-up</option>
                                    <option value="envelope">&#xf0e0; envelope </option>
                                    <option value="linkedin">&#xf0e1; linkedin </option>
                                    <option value="undo">&#xf0e2; undo </option>
                                    <option value="legal">&#xf0e3; legal</option>
                                    <option value="dashboard">&#xf0e4; dashboard</option>
                                    <option value="comment-alt">&#xf0e5; comment-alt</option>
                                    <option value="comments-alt">&#xf0e6; comments-alt </option>
                                    <option value="bolt">&#xf0e7; bolt </option>
                                    <option value="sitemap">&#xf0e8; sitemap</option>
                                    <option value="umbrella">&#xf0e9; umbrella </option>
                                    <option value="paste">&#xf0ea; paste</option>
                                    <option value="lightbulb">&#xf0eb; lightbulb</option>
                                    <option value="exchange">&#xf0ec; exchange </option>
                                    <option value="cloud-download">&#xf0ed; cloud-download </option>
                                    <option value="cloud-upload">&#xf0ee; cloud-upload </option>
                                    <option value="user-md">&#xf0f0; user-md</option>
                                    <option value="stethoscope">&#xf0f1; stethoscope</option>
                                    <option value="suitcase">&#xf0f2; suitcase </option>
                                    <option value="bell-alt">&#xf0f3; bell-alt </option>
                                    <option value="coffee">&#xf0f4; coffee </option>
                                    <option value="food">&#xf0f5; food </option>
                                    <option value="file-text-alt">&#xf0f6; file-text-alt</option>
                                    <option value="building">&#xf0f7; building </option>
                                    <option value="hospital">&#xf0f8; hospital </option>
                                    <option value="ambulance">&#xf0f9; ambulance</option>
                                    <option value="medkit">&#xf0fa; medkit </option>
                                    <option value="fighter-jet">&#xf0fb; fighter-jet</option>
                                    <option value="beer">&#xf0fc; beer </option>
                                    <option value="h-sign">&#xf0fd; h-sign </option>
                                    <option value="plus-sign-alt">&#xf0fe; plus-sign-alt</option>
                                    <option value="double-angle-left">&#xf100; double-angle-left</option>
                                    <option value="double-angle-right">&#xf101; double-angle-right </option>
                                    <option value="double-angle-up">&#xf102; double-angle-up</option>
                                    <option value="double-angle-down">&#xf103; double-angle-down</option>
                                    <option value="angle-left">&#xf104; angle-left </option>
                                    <option value="angle-right">&#xf105; angle-right</option>
                                    <option value="angle-up">&#xf106; angle-up </option>
                                    <option value="angle-down">&#xf107; angle-down </option>
                                    <option value="desktop">&#xf108; desktop</option>
                                    <option value="laptop">&#xf109; laptop </option>
                                    <option value="tablet">&#xf10a; tablet </option>
                                    <option value="mobile-phone">&#xf10b; mobile-phone </option>
                                    <option value="circle-blank">&#xf10c; circle-blank </option>
                                    <option value="quote-left">&#xf10d; quote-left </option>
                                    <option value="quote-right">&#xf10e; quote-right</option>
                                    <option value="spinner">&#xf110; spinner</option>
                                    <option value="circle">&#xf111; circle </option>
                                    <option value="reply">&#xf112; reply</option>
                                    <option value="github-alt">&#xf113; github-alt </option>
                                    <option value="folder-close-alt">&#xf114; folder-close-alt </option>
                                    <option value="folder-open-alt">&#xf115; folder-open-alt</option>
                                    <option value="expand-alt">&#xf116; expand-alt </option>
                                    <option value="collapse-alt">&#xf117; collapse-alt </option>
                                    <option value="smile">&#xf118; smile</option>
                                    <option value="frown">&#xf119; frown</option>
                                    <option value="meh">&#xf11a; meh</option>
                                    <option value="gamepad">&#xf11b; gamepad</option>
                                    <option value="keyboard">&#xf11c; keyboard </option>
                                    <option value="flag-alt">&#xf11d; flag-alt </option>
                                    <option value="flag-checkered">&#xf11e; flag-checkered </option>
                                    <option value="terminal">&#xf120; terminal </option>
                                    <option value="code">&#xf121; code </option>
                                    <option value="reply-all">&#xf122; reply-all</option>
                                    <option value="mail-reply-all">&#xf122; mail-reply-all </option>
                                    <option value="star-half-empty">&#xf123; star-half-empty</option>
                                    <option value="location-arrow">&#xf124; location-arrow </option>
                                    <option value="crop">&#xf125; crop </option>
                                    <option value="code-fork">&#xf126; code-fork</option>
                                    <option value="unlink">&#xf127; unlink </option>
                                    <option value="question">&#xf128; question </option>
                                    <option value="info">&#xf129; info </option>
                                    <option value="exclamation">&#xf12a; exclamation</option>
                                    <option value="superscript">&#xf12b; superscript</option>
                                    <option value="subscript">&#xf12c; subscript</option>
                                    <option value="eraser">&#xf12d; eraser </option>
                                    <option value="puzzle-piece">&#xf12e; puzzle-piece </option>
                                    <option value="microphone">&#xf130; microphone </option>
                                    <option value="microphone-off">&#xf131; microphone-off </option>
                                    <option value="shield">&#xf132; shield </option>
                                    <option value="calendar-empty">&#xf133; calendar-empty </option>
                                    <option value="fire-extinguisher">&#xf134; fire-extinguisher</option>
                                    <option value="rocket">&#xf135; rocket </option>
                                    <option value="maxcdn">&#xf136; maxcdn </option>
                                    <option value="chevron-sign-left">&#xf137; chevron-sign-left</option>
                                    <option value="chevron-sign-right">&#xf138; chevron-sign-right </option>
                                    <option value="chevron-sign-up">&#xf139; chevron-sign-up</option>
                                    <option value="chevron-sign-down">&#xf13a; chevron-sign-down</option>
                                    <option value="html5">&#xf13b; html5</option>
                                    <option value="css3">&#xf13c; css3 </option>
                                    <option value="anchor">&#xf13d; anchor </option>
                                    <option value="unlock-alt">&#xf13e; unlock-alt </option>
                                    <option value="bullseye">&#xf140; bullseye </option>
                                    <option value="ellipsis-horizontal">&#xf141; ellipsis-horizontal</option>
                                    <option value="ellipsis-vertical">&#xf142; ellipsis-vertical</option>
                                    <option value="rss-sign">&#xf143; rss-sign </option>
                                    <option value="play-sign">&#xf144; play-sign</option>
                                    <option value="ticket">&#xf145; ticket </option>
                                    <option value="minus-sign-alt">&#xf146; minus-sign-alt </option>
                                    <option value="check-minus">&#xf147; check-minus</option>
                                    <option value="level-up">&#xf148; level-up </option>
                                    <option value="level-down">&#xf149; level-down </option>
                                    <option value="check-sign">&#xf14a; check-sign </option>
                                    <option value="edit-sign">&#xf14b; edit-sign</option>
                                    <option value="external-link-sign">&#xf14c; external-link-sign </option>
                                    <option value="share-sign">&#xf14d; share-sign </option>
                                    <option value="compass">&#xf14e; compass</option>
                                    <option value="collapse">&#xf150; collapse </option>
                                    <option value="collapse-top">&#xf151; collapse-top </option>
                                    <option value="expand">&#xf152; expand </option>
                                    <option value="eur">&#xf153; eur</option>
                                    <option value="gbp">&#xf154; gbp</option>
                                    <option value="usd">&#xf155; usd</option>
                                    <option value="inr">&#xf156; inr</option>
                                    <option value="jpy">&#xf157; jpy</option>
                                    <option value="cny">&#xf158; cny</option>
                                    <option value="krw">&#xf159; krw</option>
                                    <option value="btc">&#xf15a; btc</option>
                                    <option value="file">&#xf15b; file </option>
                                    <option value="file-text">&#xf15c; file-text</option>
                                    <option value="sort-by-alphabet">&#xf15d; sort-by-alphabet </option>
                                    <option value="sort-by-alphabet-alt">&#xf15e; sort-by-alphabet-alt </option>
                                    <option value="sort-by-attributes">&#xf160; sort-by-attributes </option>
                                    <option value="sort-by-attributes-alt">&#xf161; sort-by-attributes-alt </option>
                                    <option value="sort-by-order">&#xf162; sort-by-order</option>
                                    <option value="sort-by-order-alt">&#xf163; sort-by-order-alt</option>
                                    <option value="thumbs-up">&#xf164; thumbs-up</option>
                                    <option value="thumbs-down">&#xf165; thumbs-down</option>
                                    <option value="youtube-sign">&#xf166; youtube-sign </option>
                                    <option value="youtube">&#xf167; youtube</option>
                                    <option value="xing">&#xf168; xing </option>
                                    <option value="xing-sign">&#xf169; xing-sign</option>
                                    <option value="youtube-play">&#xf16a; youtube-play </option>
                                    <option value="dropbox">&#xf16b; dropbox</option>
                                    <option value="stackexchange">&#xf16c; stackexchange</option>
                                    <option value="instagram">&#xf16d; instagram</option>
                                    <option value="flickr">&#xf16e; flickr </option>
                                    <option value="adn">&#xf170; adn</option>
                                    <option value="bitbucket">&#xf171; bitbucket</option>
                                    <option value="bitbucket-sign">&#xf172; bitbucket-sign </option>
                                    <option value="tumblr">&#xf173; tumblr </option>
                                    <option value="tumblr-sign">&#xf174; tumblr-sign</option>
                                    <option value="long-arrow-down">&#xf175; long-arrow-down</option>
                                    <option value="long-arrow-up">&#xf176; long-arrow-up</option>
                                    <option value="long-arrow-left">&#xf177; long-arrow-left</option>
                                    <option value="long-arrow-right">&#xf178; long-arrow-right </option>
                                    <option value="apple">&#xf179; apple</option>
                                    <option value="windows">&#xf17a; windows</option>
                                    <option value="android">&#xf17b; android</option>
                                    <option value="linux">&#xf17c; linux</option>
                                    <option value="dribbble">&#xf17d; dribbble </option>
                                    <option value="skype">&#xf17e; skype</option>
                                    <option value="foursquare">&#xf180; foursquare </option>
                                    <option value="trello">&#xf181; trello </option>
                                    <option value="female">&#xf182; female </option>
                                    <option value="male">&#xf183; male </option>
                                    <option value="gittip">&#xf184; gittip </option>
                                    <option value="sun">&#xf185; sun</option>
                                    <option value="moon">&#xf186; moon </option>
                                    <option value="archive">&#xf187; archive</option>
                                    <option value="bug">&#xf188; bug</option>
                                    <option value="vk">&#xf189; vk </option>
                                    <option value="weibo">&#xf18a; weibo</option>
                                    <option value="renren">&#xf18b; renren </option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <button type="submit" class="btn btn-success waves-effect waves-light">
                                    <span class="btn-label"><i class="fa fa-check"></i></span>Salvar
                                </button> 
                                <button type="button" data-dismiss="modal" class="btn btn-danger waves-effect waves-light">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>